export const Agent = [
    {
      id: 1,
      img: "https://cdn.brandfetch.io/idxVhszl6V/w/400/h/400/theme/dark/icon.jpeg-1.jpg",
      name: "Agent Alpha",
      type: "Linux",
      version: "v2.0.1",
      status: "Disconnected",
      exportedVolume: "150 GB",
      logs: "",
      metrics: "700KB/h",
      traces: "",
      configuration:"",
      pipelineName:"",
      selected:false
    },
    {
      id: 2,
      img: "https://cdn.brandfetch.io/idxVhszl6V/w/400/h/400/theme/dark/icon.jpeg",
      name: "Agent Beta",
      type: "Windows",
      version: "v1.3.5",
      status: "Disconnected",
      exportedVolume: "85 GB",
      logs: "",
      metrics: "600KB/h",
      traces: "",
      configuration:"",
      pipelineName:"",
      selected:false
    },
    {
      id: 3,
      img: "https://cdn.brandfetch.io/idxVhszl6V/w/400/h/400/theme/dark/icon.jpeg-2.jpg",
      name: "Agent Gamma",
      type: "MacOS",
      version: "v3.1.0",
      status: "Disconnected",
      exportedVolume: "200 GB",
      logs: "",
      metrics: "800KB/h",
      traces: "",
      configuration:"",
      pipelineName:"",
      selected:false
    },
    {
      id: 4,
      img: "https://cdn.brandfetch.io/idxVhszl6V/w/400/h/400/theme/dark/icon.jpeg-3.jpg",
      name: "Agent Delta",
      type: "Linux",
      version: "v2.2.3",
      status: "Disconnected",
      exportedVolume: "120 GB",
      logs: "",
      metrics: "500KB/h",
      traces: "",
      configuration:"",
      pipelineName:"",
      selected:false
    },
  ];